Repository victorbalssa/abacus, pull requests merged in 2024-01, with the labels that each got.

#214 version/0.11.1
  .github/CONTRIBUTING.md
  .github/HELP.md
  .github/PRIVACY_POLICY.md
  .github/dependabot.yml
  .github/img.png
  .github/img_2.jpeg
  app.json
  package-lock.json
  package.json
  src/components/Charts/AssetsHistoryChart.tsx
  src/components/Charts/BalanceHistoryChart.tsx
  src/components/Forms/Fields/AutocompleteField.tsx
  src/components/Forms/Fields/GroupTitle.tsx
  src/components/Forms/OauthForm.tsx
  src/components/Forms/TransactionForm.tsx
  src/components/Screens/ChartScreen.tsx
  src/components/Screens/HomeScreen.tsx
  src/components/Screens/OauthScreen.tsx
  src/components/Screens/TransactionsScreen.tsx
  src/components/UI/ALibrary/AIconButton.tsx
  src/components/UI/ALibrary/AStack.tsx
  src/components/UI/ALibrary/AText.tsx
  src/components/UI/ErrorWidget.tsx
  src/components/UI/Filters.tsx
  src/components/UI/NavigationHeader.tsx
  src/constants/colors.ts
  src/constants/oauth.ts
  src/i18n/locale/translations/de-DE.ts
  src/i18n/locale/translations/en-US.ts
  src/i18n/locale/translations/es-ES.ts
  src/i18n/locale/translations/fr-FR.ts
  src/i18n/locale/translations/id-ID.ts
  src/i18n/locale/translations/index.ts
  src/i18n/locale/translations/it-IT.ts
  src/i18n/locale/translations/pt-BR.ts
  src/i18n/locale/translations/ru-RU.ts
  src/i18n/locale/translations/sl-SI.ts
  src/i18n/locale/translations/zh-CN.ts
  src/lib/common.ts
  src/models/accounts.ts
  src/models/configuration.ts
  src/models/firefly.ts
  src/models/transactions.ts
  src/routes/index.tsx
Labels: dependencies, eas-build

#231 chinese translation
  src/i18n/locale/translations/zh-CN.ts
Labels: translation

#237 version/0.11.2
  src/components/Charts/AssetsHistoryChart.tsx
  src/components/Charts/BalanceHistoryChart.tsx
  src/components/Forms/OauthForm.tsx
  src/components/Screens/ChartScreen.tsx
  src/components/Screens/HomeScreen.tsx
  src/components/Screens/TransactionsScreen.tsx
  src/components/UI/ALibrary/AStack.tsx
  src/components/UI/ErrorBoundary.tsx
  src/components/UI/Filters.tsx
  src/components/UI/NavigationHeader.tsx
Labels: eas-build
